# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subjectText = QtWidgets.QTextEdit(self.centralwidget)
        self.subjectText.setGeometry(QtCore.QRect(210, 60, 491, 41))
        self.subjectText.setObjectName("subjectText")
        self.subject = QtWidgets.QLabel(self.centralwidget)
        self.subject.setGeometry(QtCore.QRect(70, 60, 89, 23))
        self.subject.setObjectName("subject")
        self.body = QtWidgets.QLabel(self.centralwidget)
        self.body.setGeometry(QtCore.QRect(70, 130, 89, 23))
        self.body.setObjectName("body")
        self.bodyText = QtWidgets.QTextEdit(self.centralwidget)
        self.bodyText.setGeometry(QtCore.QRect(210, 130, 491, 201))
        self.bodyText.setObjectName("bodyText")
        self.attachment = QtWidgets.QCheckBox(self.centralwidget)
        self.attachment.setGeometry(QtCore.QRect(80, 370, 141, 29))
        self.attachment.setObjectName("attachment")
        self.attachmentFolder = QtWidgets.QPushButton(self.centralwidget)
        self.attachmentFolder.setEnabled(True)
        self.attachmentFolder.setGeometry(QtCore.QRect(290, 370, 411, 33))
        self.attachmentFolder.setObjectName("attachmentFolder")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(300, 460, 191, 41))
        self.submit.setObjectName("submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subject.setText(_translate("MainWindow", "Subject"))
        self.body.setText(_translate("MainWindow", "Body"))
        self.attachment.setText(_translate("MainWindow", " Attachment"))
        self.attachmentFolder.setText(_translate("MainWindow", "Select Folder"))
        self.submit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
