# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/email_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# from PyQt5.QtWidgets import QMessageBox
# from PyQt5 import QtCore, QtWidgets
from PyQt5 import QtWidgets, QtGui, QtCore
from credentials import Ui_Form
import sys
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subjectText = QtWidgets.QTextEdit(self.centralwidget)
        self.subjectText.setGeometry(QtCore.QRect(210, 40, 491, 41))
        self.subjectText.setObjectName("subjectText")
        self.subject = QtWidgets.QLabel(self.centralwidget)
        self.subject.setGeometry(QtCore.QRect(70, 40, 89, 23))
        self.subject.setObjectName("subject")
        self.body = QtWidgets.QLabel(self.centralwidget)
        self.body.setGeometry(QtCore.QRect(70, 110, 89, 23))
        self.body.setObjectName("body")
        self.bodyText = QtWidgets.QTextEdit(self.centralwidget)
        self.bodyText.setGeometry(QtCore.QRect(210, 110, 491, 181))
        self.bodyText.setObjectName("bodyText")
        self.attachment = QtWidgets.QCheckBox(self.centralwidget)
        self.attachment.setGeometry(QtCore.QRect(70, 330, 141, 29))
        self.attachment.setObjectName("attachment")
        self.attachment.clicked.connect(self.isAttachment)

        self.attachmentSelect = QtWidgets.QPushButton(self.centralwidget)
        self.attachmentSelect.setEnabled(True)
        self.attachmentSelect.setGeometry(QtCore.QRect(290, 330, 411, 33))
        self.attachmentSelect.setObjectName("attachmentSelect")
        self.attachmentSelect.setEnabled(False)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(290, 480, 191, 41))
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.nextWindow)

        self.csvSelect = QtWidgets.QPushButton(self.centralwidget)
        self.csvSelect.setGeometry(QtCore.QRect(290, 390, 411, 33))
        self.csvSelect.setObjectName("csvSelect")
        self.csvSelect.clicked.connect(self.getcsv)

        self.recipientsList = QtWidgets.QLabel(self.centralwidget)
        self.recipientsList.setGeometry(QtCore.QRect(70, 390, 141, 23))
        self.recipientsList.setObjectName("recipientsList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subject.setText(_translate("MainWindow", "Subject"))
        self.body.setText(_translate("MainWindow", "Body"))
        self.attachment.setText(_translate("MainWindow", " Attachment"))
        self.attachmentSelect.setText(_translate("MainWindow", "Select Folder"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.csvSelect.setText(_translate("MainWindow", "Add File"))
        self.recipientsList.setText(_translate("MainWindow", "Recipients List"))

    def isAttachment(self):
        if(self.attachment.isChecked()==True):
            self.attachmentSelect.setEnabled(True)        
        else:
            self.attachmentSelect.setEnabled(False)

    def validateData(self):
        if self.subjectText.toPlainText().strip()=="" or self.bodyText.toPlainText().strip() == "":
            self.showPopup()
        
    
    def showPopup(self):
        pop = QtGui.QMessageBox()
        pop.setWindowTitle("Warning")
        pop.setText("Enter Valid Data")
        pop.setIcon(QtGui.QMessageBox.Warning)
        x = pop.exec_()

    def getcsv(self):
        self.dialog = Main()
        self.dialog.browse()
       
        

    def nextWindow(self):
        self.validateData()
        subjectText = self.subjectText.toPlainText()
        bodyText = self.bodyText.toPlainText()

        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()

class Main(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def browse(self):
        dialog = QtWidgets.QFileDialog(self)
        dialog.setWindowTitle('Open Recipients list file')
        dialog.setNameFilter('(*.csv)')
        dialog.setFileMode(QtWidgets.QFileDialog.ExistingFile)
        filename = None
        if dialog.exec_() == QtWidgets.QDialog.Accepted:
            filename = dialog.selectedFiles()
        if filename:
            self.fname = str(filename[0])
            print(self.fname)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
